### ISSUE TITLE
set_commit_stats never runs

### ISSUE THREAD

**Issue by mattgenious** [codersrank-org/repo_info_extractor#11]
## Expected Behavior
run main.py with directory argument
get a zipped json file containing contribution information

## Actual Behavior
run main.py with directory argument

get a zipped file containing contribution information except all commits are missing elements in the changedFiles array like this:
```
            "authorEmail": "373ffeff04c386969edac0edc2cf2628", 
            "isDuplicated": false, 
            "authorName": "fa20e926ccd1e69da76a9bb5caeb826b", 
            "parents": [
                "545522fdab9c25a1ce8a8ef5c6dfbee6804e115c"
            ], 
            "commitHash": "ae3e69f87557e3825f84db37860019d2a213183e", 
            "isMerge": false, 
            "changedFiles": [], 
            "createdAt": "2019-06-17 14:48:20"
```

## Steps to Reproduce the Problem

  1. run main.py with valid git repository as argument

## Specifications

  - Platform: Windows 10 1903 build 18932.1000
  - Python: 2.7.16

**Comment by seigieu** [comment]
This project (Codersrank) seems to be dead before even started...

**Comment by mattgenious** [comment]
What makes you say that?

**Comment by peti2001** [comment]
We might not have enough resources for everything but we are definitely not dead :)

**Comment by seigieu** [comment]
Wanted to check if someone at last reads it :P sorry! 🙏

**Comment by peti2001** [comment]
We have a proposed solution for this. See pr #25. The problem is with the multi-threading. It works in a different in Windows and Unix/Linux. Global variables are not updated by the different threads in Windows. 
Unfortunately, this is much slower in Windows than on other platforms because of the multi-threading implementation of Python in Windows. It has to serialize (pickle) the data to pass data between threads.

You can try it like this:
```
git fetch origin pull/25/head:pr-25
git checkout pr-25
```
