### ISSUE TITLE
Support extracting imported Perl modules as libraries

### ISSUE THREAD

**Issue by ferki** [codersrank-org/repo_info_extractor#129]
Perl has two slightly different ways to import code from other modules: [`require`](https://perldoc.pl/functions/require) and [`use`](https://perldoc.pl/functions/use). If I understand correctly, we'd have to extract the module names from these statements in order to allow CodersRank to treat them as libraries.

Part of the complexity is that both import methods have quite a few different format. I'm not sure if regular expressions are the best approach to parse all the variations, but my initial attempts seem to be able to handle at least the most important (common?) forms.

If this is an interesting direction, I'm willing to prepare a pull request with at least a starting point.

**Comment by peti2001** [comment]
Hi @ferki,

This is something very interesting and if you can create a pull request that would be a great help. You don't have to rely on regexes for example for HTML we use HTML parser: https://github.com/codersrank-org/repo_info_extractor/blob/master/src/language/HTML.py
However, I think for Perl regex is the best approach. It must be fast because it will be used for each commit made by the given author and it will check all the Perl files which have been updated.

To add the support you just have to create the Perl.py file and implement the `extract_libraries(files):` function.

**Comment by ferki** [comment]
To programmatically understand Perl code, I would ideally use [PPI](https://metacpan.org/pod/PPI) to build a PDOM (Perl Document Object Model, sort of abstract syntax tree), or perhaps [PPR](https://metacpan.org/pod/PPR) to extract the interesting parts. Unfortunately I have no idea how I could use those from Python code easily, so I just leave that note here for future reference.

I'll go forward and open a PR with a regex based initial approach soon. I believe that would be at least a "good enough" trade-off between the different aspects.

**Comment by peti2001** [comment]
This is a good approach. I have merged your PR and your change is live already. If you want to highlight a few libraries on your profile, you can do it by adding them to this repo: https://github.com/codersrank-org/libraries

**Comment by ferki** [comment]
Thanks, @peti2001! Yes, I expected adding libraries to that other repo as next step :+1: I'll try to collect some popular ones, to maximize the benefit for others as well :)
