### ISSUE TITLE
Extract from Mercurial

### ISSUE THREAD

**Issue by Awilum** [codersrank-org/repo_info_extractor#196]
Is it possible to extract data from Mercurial repository ?

I a have a lot of code created by me using Mercurial Revision Control for my private projects. 
Is it possible somehow to export/import all that data to My Codersrank Profile ?

**Comment by peti2001** [comment]
Hi @Awilum,

No, it is not possible. And we are not planning to implement it because there is no demand for it. If it changes or course we can consider adding mercurial support.
The best you can do is to convert your hg repo to git. Like this: https://markheath.net/post/how-to-convert-mercurial-repository-to.
